name: BOVN Auto Crawler

on:
  schedule:
    - cron: '0 1 * * *' # Tự chạy mỗi ngày lúc 8h sáng giờ VN
  workflow_dispatch: # Cho phép bấm chạy thủ công bất kỳ lúc nào

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Bot Script
        env:
          GAS_WEBHOOK_URL: ${{ secrets.GAS_WEBHOOK_URL }}
        run: node index.js
